## Linear Discriminants

## LDA

In [1]:
library(MASS)

In [2]:
turtles <- read.csv("../Data/turtles.csv")

In [3]:
turtles.lda = lda(Gender ~., data=turtles)  # ~. = all the other variables
table(turtles$Gender, predict(turtles.lda)$class)

         female male
  female     20    4
  male        0   24

In [4]:
turtles.lda.cv=lda(Gender ~., CV=TRUE, data = turtles)
table(turtles$Gender, turtles.lda.cv$class)

         female male
  female     19    5
  male        1   23

In [10]:
turtles.lda.xval=rep(0, length = 48)
x=rep(1:10, length = 48)
x

 [1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5
[26]  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8

In [12]:
# Scrambles the order of the numbers
x=sample(x)
x

 [1]  3  6  8  7  3  6  7  1 10  6  2  5  2  4  1  8  1 10  7  9  3  4  7  7  5
[26] 10  6  1  9  5  8  3  9 10  9  8  2  5  4  2  2  4  1  4  8  5  6  3

In [13]:
for(i in 1:10){
    train = turtles[x!=1,]
    test = turtles[x==i,]
    glub = lda(Gender~Length+Width+Height, data=train)
    turtles.lda.xval[x==i]=predict(glub,test)$class
}

table(turtles$Gender, turtles.lda.xval)

        turtles.lda.xval
          1  2
  female 20  4
  male    0 24

## QDA

In [14]:
turtles.qda = qda(Gender ~., data=turtles)  # ~. = all the other variables
table(turtles$Gender, predict(turtles.lda)$class)

         female male
  female     20    4
  male        0   24

In [15]:
turtles.qda.cv=qda(Gender ~., CV=TRUE, data = turtles)
table(turtles$Gender, turtles.qda.cv$class)

         female male
  female     21    3
  male        2   22

In [16]:
turtles.qda.xval=rep(0, length = 48)
x=rep(1:10, length = 48)
x

 [1]  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5
[26]  6  7  8  9 10  1  2  3  4  5  6  7  8  9 10  1  2  3  4  5  6  7  8

In [17]:
# Scrambles the order of the numbers
x=sample(x)
x

 [1]  9 10  7  8  3  4  3  3  7  5  2  8  1  4  2  9  7  5  5  4  9 10  5  1  6
[26]  5  6  8 10  4  7  1  6  1  6  2  7  8  6  4 10  3  1  2  3  8  9  2

In [18]:
for(i in 1:10){
    train = turtles[x!=1,]
    test = turtles[x==i,]
    glub = qda(Gender~Length+Width+Height, data=train)
    turtles.qda.xval[x==i]=predict(glub,test)$class
}

table(turtles$Gender, turtles.qda.xval)

        turtles.qda.xval
          1  2
  female 21  3
  male    0 24